version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bank_operation'
      MYSQL_USER: 'pismo'
      MYSQL_PASSWORD: 'pismopass'
      MYSQL_ROOT_PASSWORD: 'pismoroot'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: