version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bank_operation'
      MYSQL_USER: 'pismo'
      MYSQL_PASSWORD: 'pismopass'
      MYSQL_ROOT_PASSWORD: 'pismoroot'
      TZ: "UTC"
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  api-bank-operation:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank_operation?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pismo
      SPRING_DATASOURCE_PASSWORD: pismopass
    ports:
      - '8082:8080'

volumes:
  mysql_data: